name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Env
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build and Push Docker Image
        id: set-version
        run: |
          SHA=${{ env.sha_short }}
          echo "version=${SHA}" >> $GITHUB_ENV
          docker build ./ -f Dockerfile -t ${{ secrets.DOCKER_USER }}/nws-app:$SHA
          docker push ${{ secrets.DOCKER_USER }}/nws-app:$SHA
      
  modify-manifest:
    needs: build-and-push
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        name: update manifest repo
        with:
          repository: 'ngnrng/NWS-weather-app-manifest'
          token: ${{ secrets.GIT_TOKEN }}

      - name: Set SHA Short
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Update yaml files
        run: |
          set -x
          owner="ngnrng"
          branch="main"
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git config --global user.name "kevops-atl"
          git checkout $branch
          echo ${{ env.sha_short }}
          cat cronjob.yaml
          echo "Modifying $file"
          sed -i "s|image: ${{ secrets.DOCKER_USER }}/nws-forecast-data:.*|image: ${{ secrets.DOCKER_USER }}/nws-forecast-data:${{ env.sha_short }}|g" cronjob.yaml
          git add .
          git commit -m "image ${{ env.sha_short }}"
          git push

      # - name: Commit and push changes
      #   run: |
      #     owner="ngnrng"
      #     branch="main"
      #     git config --global user.email ${{ secrets.GIT_EMAIL }}
      #     git config --global user.name "kevops-atl"
      #     git checkout $branch
      #     echo ${{ env.sha_short }}
      #     git add .
      #     git commit -m "image ${{ env.sha_short }}"
      #     git push origin main
      